language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install: 
  - pip install Cython --use-mirrors
  - cd wrappers/Python
  - python setup.py install # Install CoolProp
# command to run tests
script: 
  - cd CoolProp/tests
  - nosetests

notifications:
  email:
    recipients:
      - ian.h.bell@gmail.com
    on_success: never # default: change
    on_failure: always # default: always