language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: 
  - gcc -v
  - pip -q install cython --install-option="--no-cython-compile"
  - cd wrappers/Python
  - python setup.py install # Install CoolProp
# command to run tests
script: 
  - cd CoolProp/tests # relative to wrappers/Python
  - nosetests

notifications:
  email:
    recipients:
      - ian.h.bell@gmail.com
    on_success: never # default: change
    on_failure: always # default: always